// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base_service.proto

#ifndef PROTOBUF_base_5fservice_2eproto__INCLUDED
#define PROTOBUF_base_5fservice_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace PocoRpc {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_base_5fservice_2eproto();
void protobuf_AssignDesc_base_5fservice_2eproto();
void protobuf_ShutdownFile_base_5fservice_2eproto();

class PingReq;
class PingReply;
class GetServiceListReq;
class GetServiceListReply;

// ===================================================================

class PingReq : public ::google::protobuf::Message {
 public:
  PingReq();
  virtual ~PingReq();

  PingReq(const PingReq& from);

  inline PingReq& operator=(const PingReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PingReq& default_instance();

  void Swap(PingReq* other);

  // implements Message ----------------------------------------------

  PingReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PingReq& from);
  void MergeFrom(const PingReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:PocoRpc.PingReq)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_base_5fservice_2eproto();
  friend void protobuf_AssignDesc_base_5fservice_2eproto();
  friend void protobuf_ShutdownFile_base_5fservice_2eproto();

  void InitAsDefaultInstance();
  static PingReq* default_instance_;
};
// -------------------------------------------------------------------

class PingReply : public ::google::protobuf::Message {
 public:
  PingReply();
  virtual ~PingReply();

  PingReply(const PingReply& from);

  inline PingReply& operator=(const PingReply& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PingReply& default_instance();

  void Swap(PingReply* other);

  // implements Message ----------------------------------------------

  PingReply* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PingReply& from);
  void MergeFrom(const PingReply& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 status = 1;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 1;
  inline ::google::protobuf::uint32 status() const;
  inline void set_status(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:PocoRpc.PingReply)
 private:
  inline void set_has_status();
  inline void clear_has_status();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 status_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_base_5fservice_2eproto();
  friend void protobuf_AssignDesc_base_5fservice_2eproto();
  friend void protobuf_ShutdownFile_base_5fservice_2eproto();

  void InitAsDefaultInstance();
  static PingReply* default_instance_;
};
// -------------------------------------------------------------------

class GetServiceListReq : public ::google::protobuf::Message {
 public:
  GetServiceListReq();
  virtual ~GetServiceListReq();

  GetServiceListReq(const GetServiceListReq& from);

  inline GetServiceListReq& operator=(const GetServiceListReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetServiceListReq& default_instance();

  void Swap(GetServiceListReq* other);

  // implements Message ----------------------------------------------

  GetServiceListReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetServiceListReq& from);
  void MergeFrom(const GetServiceListReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:PocoRpc.GetServiceListReq)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_base_5fservice_2eproto();
  friend void protobuf_AssignDesc_base_5fservice_2eproto();
  friend void protobuf_ShutdownFile_base_5fservice_2eproto();

  void InitAsDefaultInstance();
  static GetServiceListReq* default_instance_;
};
// -------------------------------------------------------------------

class GetServiceListReply : public ::google::protobuf::Message {
 public:
  GetServiceListReply();
  virtual ~GetServiceListReply();

  GetServiceListReply(const GetServiceListReply& from);

  inline GetServiceListReply& operator=(const GetServiceListReply& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetServiceListReply& default_instance();

  void Swap(GetServiceListReply* other);

  // implements Message ----------------------------------------------

  GetServiceListReply* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetServiceListReply& from);
  void MergeFrom(const GetServiceListReply& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 status = 1;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 1;
  inline ::google::protobuf::uint32 status() const;
  inline void set_status(::google::protobuf::uint32 value);

  // repeated string service_list = 2;
  inline int service_list_size() const;
  inline void clear_service_list();
  static const int kServiceListFieldNumber = 2;
  inline const ::std::string& service_list(int index) const;
  inline ::std::string* mutable_service_list(int index);
  inline void set_service_list(int index, const ::std::string& value);
  inline void set_service_list(int index, const char* value);
  inline void set_service_list(int index, const char* value, size_t size);
  inline ::std::string* add_service_list();
  inline void add_service_list(const ::std::string& value);
  inline void add_service_list(const char* value);
  inline void add_service_list(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& service_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_service_list();

  // @@protoc_insertion_point(class_scope:PocoRpc.GetServiceListReply)
 private:
  inline void set_has_status();
  inline void clear_has_status();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::std::string> service_list_;
  ::google::protobuf::uint32 status_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_base_5fservice_2eproto();
  friend void protobuf_AssignDesc_base_5fservice_2eproto();
  friend void protobuf_ShutdownFile_base_5fservice_2eproto();

  void InitAsDefaultInstance();
  static GetServiceListReply* default_instance_;
};
// ===================================================================

class BaseService_Stub;

class BaseService : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline BaseService() {};
 public:
  virtual ~BaseService();

  typedef BaseService_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void Ping(::google::protobuf::RpcController* controller,
                       const ::PocoRpc::PingReq* request,
                       ::PocoRpc::PingReply* response,
                       ::google::protobuf::Closure* done);
  virtual void GetServiceList(::google::protobuf::RpcController* controller,
                       const ::PocoRpc::GetServiceListReq* request,
                       ::PocoRpc::GetServiceListReply* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(BaseService);
};

class BaseService_Stub : public BaseService {
 public:
  BaseService_Stub(::google::protobuf::RpcChannel* channel);
  BaseService_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~BaseService_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements BaseService ------------------------------------------

  void Ping(::google::protobuf::RpcController* controller,
                       const ::PocoRpc::PingReq* request,
                       ::PocoRpc::PingReply* response,
                       ::google::protobuf::Closure* done);
  void GetServiceList(::google::protobuf::RpcController* controller,
                       const ::PocoRpc::GetServiceListReq* request,
                       ::PocoRpc::GetServiceListReply* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(BaseService_Stub);
};


// ===================================================================


// ===================================================================

// PingReq

// -------------------------------------------------------------------

// PingReply

// required uint32 status = 1;
inline bool PingReply::has_status() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PingReply::set_has_status() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PingReply::clear_has_status() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PingReply::clear_status() {
  status_ = 0u;
  clear_has_status();
}
inline ::google::protobuf::uint32 PingReply::status() const {
  return status_;
}
inline void PingReply::set_status(::google::protobuf::uint32 value) {
  set_has_status();
  status_ = value;
}

// -------------------------------------------------------------------

// GetServiceListReq

// -------------------------------------------------------------------

// GetServiceListReply

// required uint32 status = 1;
inline bool GetServiceListReply::has_status() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetServiceListReply::set_has_status() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetServiceListReply::clear_has_status() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetServiceListReply::clear_status() {
  status_ = 0u;
  clear_has_status();
}
inline ::google::protobuf::uint32 GetServiceListReply::status() const {
  return status_;
}
inline void GetServiceListReply::set_status(::google::protobuf::uint32 value) {
  set_has_status();
  status_ = value;
}

// repeated string service_list = 2;
inline int GetServiceListReply::service_list_size() const {
  return service_list_.size();
}
inline void GetServiceListReply::clear_service_list() {
  service_list_.Clear();
}
inline const ::std::string& GetServiceListReply::service_list(int index) const {
  return service_list_.Get(index);
}
inline ::std::string* GetServiceListReply::mutable_service_list(int index) {
  return service_list_.Mutable(index);
}
inline void GetServiceListReply::set_service_list(int index, const ::std::string& value) {
  service_list_.Mutable(index)->assign(value);
}
inline void GetServiceListReply::set_service_list(int index, const char* value) {
  service_list_.Mutable(index)->assign(value);
}
inline void GetServiceListReply::set_service_list(int index, const char* value, size_t size) {
  service_list_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* GetServiceListReply::add_service_list() {
  return service_list_.Add();
}
inline void GetServiceListReply::add_service_list(const ::std::string& value) {
  service_list_.Add()->assign(value);
}
inline void GetServiceListReply::add_service_list(const char* value) {
  service_list_.Add()->assign(value);
}
inline void GetServiceListReply::add_service_list(const char* value, size_t size) {
  service_list_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
GetServiceListReply::service_list() const {
  return service_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
GetServiceListReply::mutable_service_list() {
  return &service_list_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace PocoRpc

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_base_5fservice_2eproto__INCLUDED
